# Generated by Django 4.2.6 on 2023-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_evento_estado_alter_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
